using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookingMeetingRooms.Migrations
{
    /// <inheritdoc />
    public partial class ChangeIdsToInt32 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Видаляємо всі дані перед зміною типів (UUID не можна конвертувати в integer)
            migrationBuilder.Sql("DELETE FROM \"BookingStatusTransitions\"");
            migrationBuilder.Sql("DELETE FROM \"BookingRequests\"");
            migrationBuilder.Sql("DELETE FROM \"Rooms\"");

            // Видаляємо foreign key constraints перед зміною типів
            migrationBuilder.DropForeignKey(
                name: "FK_BookingRequests_Rooms_RoomId",
                table: "BookingRequests");

            migrationBuilder.DropForeignKey(
                name: "FK_BookingStatusTransitions_BookingRequests_BookingRequestId",
                table: "BookingStatusTransitions");

            // Змінюємо типи колонок з використанням USING для явного приведення
            migrationBuilder.Sql("ALTER TABLE \"Rooms\" ALTER COLUMN \"Id\" TYPE integer USING 0");
            migrationBuilder.Sql("ALTER TABLE \"Rooms\" ALTER COLUMN \"Id\" DROP DEFAULT");
            migrationBuilder.Sql("ALTER TABLE \"Rooms\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY");

            migrationBuilder.Sql("ALTER TABLE \"BookingStatusTransitions\" ALTER COLUMN \"ChangedByUserId\" TYPE integer USING 0");
            migrationBuilder.Sql("ALTER TABLE \"BookingStatusTransitions\" ALTER COLUMN \"BookingRequestId\" TYPE integer USING 0");
            migrationBuilder.Sql("ALTER TABLE \"BookingStatusTransitions\" ALTER COLUMN \"Id\" TYPE integer USING 0");
            migrationBuilder.Sql("ALTER TABLE \"BookingStatusTransitions\" ALTER COLUMN \"Id\" DROP DEFAULT");
            migrationBuilder.Sql("ALTER TABLE \"BookingStatusTransitions\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY");

            migrationBuilder.Sql("ALTER TABLE \"BookingRequests\" ALTER COLUMN \"RoomId\" TYPE integer USING 0");
            migrationBuilder.Sql("ALTER TABLE \"BookingRequests\" ALTER COLUMN \"CreatedByUserId\" TYPE integer USING 0");
            migrationBuilder.Sql("ALTER TABLE \"BookingRequests\" ALTER COLUMN \"Id\" TYPE integer USING 0");
            migrationBuilder.Sql("ALTER TABLE \"BookingRequests\" ALTER COLUMN \"Id\" DROP DEFAULT");
            migrationBuilder.Sql("ALTER TABLE \"BookingRequests\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY");

            // Відновлюємо foreign key constraints
            migrationBuilder.AddForeignKey(
                name: "FK_BookingRequests_Rooms_RoomId",
                table: "BookingRequests",
                column: "RoomId",
                principalTable: "Rooms",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_BookingStatusTransitions_BookingRequests_BookingRequestId",
                table: "BookingStatusTransitions",
                column: "BookingRequestId",
                principalTable: "BookingRequests",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<Guid>(
                name: "Id",
                table: "Rooms",
                type: "uuid",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer")
                .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            migrationBuilder.AlterColumn<Guid>(
                name: "ChangedByUserId",
                table: "BookingStatusTransitions",
                type: "uuid",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer");

            migrationBuilder.AlterColumn<Guid>(
                name: "BookingRequestId",
                table: "BookingStatusTransitions",
                type: "uuid",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer");

            migrationBuilder.AlterColumn<Guid>(
                name: "Id",
                table: "BookingStatusTransitions",
                type: "uuid",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer")
                .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            migrationBuilder.AlterColumn<Guid>(
                name: "RoomId",
                table: "BookingRequests",
                type: "uuid",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer");

            migrationBuilder.AlterColumn<Guid>(
                name: "CreatedByUserId",
                table: "BookingRequests",
                type: "uuid",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer");

            migrationBuilder.AlterColumn<Guid>(
                name: "Id",
                table: "BookingRequests",
                type: "uuid",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer")
                .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
        }
    }
}
