using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookingMeetingRooms.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Создаем таблицы только если они не существуют
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Rooms"" (
                    ""Id"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" character varying(200) NOT NULL,
                    ""Capacity"" integer NOT NULL,
                    ""Location"" character varying(200) NOT NULL,
                    ""IsActive"" boolean NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_Rooms"" PRIMARY KEY (""Id"")
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Users"" (
                    ""Id"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" character varying(200) NOT NULL,
                    ""Email"" character varying(200) NOT NULL,
                    ""Role"" text NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_Users"" PRIMARY KEY (""Id"")
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""BookingRequests"" (
                    ""Id"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                    ""RoomId"" integer NOT NULL,
                    ""StartAt"" timestamp with time zone NOT NULL,
                    ""EndAt"" timestamp with time zone NOT NULL,
                    ""ParticipantEmails"" text NOT NULL,
                    ""Description"" character varying(1000) NOT NULL,
                    ""Status"" text NOT NULL,
                    ""CreatedByUserId"" integer NOT NULL,
                    ""RowVersion"" bytea NOT NULL DEFAULT md5(random()::text)::bytea,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_BookingRequests"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_BookingRequests_Rooms_RoomId"" FOREIGN KEY (""RoomId"") REFERENCES ""Rooms"" (""Id"") ON DELETE RESTRICT
                );
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""BookingStatusTransitions"" (
                    ""Id"" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                    ""BookingRequestId"" integer NOT NULL,
                    ""FromStatus"" text NOT NULL,
                    ""ToStatus"" text NOT NULL,
                    ""ChangedByUserId"" integer NOT NULL,
                    ""Reason"" character varying(500) NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL,
                    ""UpdatedAt"" timestamp with time zone NULL,
                    CONSTRAINT ""PK_BookingStatusTransitions"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_BookingStatusTransitions_BookingRequests_BookingRequestId"" FOREIGN KEY (""BookingRequestId"") REFERENCES ""BookingRequests"" (""Id"") ON DELETE CASCADE
                );
            ");

            // Создаем индексы только если они не существуют
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_BookingRequests_CreatedByUserId"" ON ""BookingRequests"" (""CreatedByUserId"");
                CREATE INDEX IF NOT EXISTS ""IX_BookingRequests_RoomId_Status"" ON ""BookingRequests"" (""RoomId"", ""Status"");
                CREATE INDEX IF NOT EXISTS ""IX_BookingRequests_Status"" ON ""BookingRequests"" (""Status"");
                CREATE INDEX IF NOT EXISTS ""IX_BookingStatusTransitions_BookingRequestId"" ON ""BookingStatusTransitions"" (""BookingRequestId"");
                CREATE INDEX IF NOT EXISTS ""IX_Rooms_IsActive"" ON ""Rooms"" (""IsActive"");
                CREATE INDEX IF NOT EXISTS ""IX_Rooms_Location"" ON ""Rooms"" (""Location"");
                CREATE INDEX IF NOT EXISTS ""IX_Rooms_Location_IsActive"" ON ""Rooms"" (""Location"", ""IsActive"");
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_Users_Email"" ON ""Users"" (""Email"");
            ");

            // Обновляем RowVersion для существующих таблиц, если нужно
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.columns 
                               WHERE table_name = 'BookingRequests' AND column_name = 'RowVersion' 
                               AND column_default IS NULL) THEN
                        ALTER TABLE ""BookingRequests"" 
                        ALTER COLUMN ""RowVersion"" SET DEFAULT md5(random()::text)::bytea;
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "BookingStatusTransitions");

            migrationBuilder.DropTable(
                name: "Users");

            migrationBuilder.DropTable(
                name: "BookingRequests");

            migrationBuilder.DropTable(
                name: "Rooms");
        }
    }
}
